/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerAccessPointsRouteImport } from './routes/owner.access-points'
import { Route as OwnerAuditLogsRouteImport } from './routes/owner.audit-logs'
import { Route as OwnerAuthorityProductsRouteImport } from './routes/owner.authority-products'
import { Route as OwnerBudgetManagersRouteImport } from './routes/owner.budget-managers'
import { Route as OwnerBudgetPoliciesRouteImport } from './routes/owner.budget-policies'
import { Route as OwnerCreditsRouteImport } from './routes/owner.credits'
import { Route as OwnerKeysRouteImport } from './routes/owner.keys'
import { Route as OwnerPlansRouteImport } from './routes/owner.plans'
import { Route as OwnerPricingRouteImport } from './routes/owner.pricing'
import { Route as OwnerProvidersRouteImport } from './routes/owner.providers'
import { Route as OwnerRequestLogsRouteImport } from './routes/owner.request-logs'
import { Route as OwnerSystemSettingsRouteImport } from './routes/owner.system-settings'
import { Route as OwnerTeamsRouteImport } from './routes/owner.teams'
import { Route as OwnerUsersRouteImport } from './routes/owner.users'
import { Route as OwnerAccountSecurityRouteImport } from './routes/owner.account.security'
import { Route as OwnerOperationsCardActivationsRouteImport } from './routes/owner.operations.card-activations'
import { Route as OwnerOperationsGrantsRouteImport } from './routes/owner.operations.grants'
import { Route as OwnerPlansAndBudgetsBudgetPoliciesRouteImport } from './routes/owner.plans-and-budgets.budget-policies'
import { Route as OwnerPlansAndBudgetsGovernanceBudgetsRouteImport } from './routes/owner.plans-and-budgets.governance-budgets'
import { Route as OwnerPlansAndBudgetsPlanPurchasesRouteImport } from './routes/owner.plans-and-budgets.plan-purchases'
import { Route as OwnerPlansAndBudgetsPlansRouteImport } from './routes/owner.plans-and-budgets.plans'
import { Route as OwnerPlansIndexRouteImport } from './routes/owner.plans.index'
import { Route as OwnerPlansSubscriptionsRouteImport } from './routes/owner.plans.subscriptions'
import { Route as OwnerTeamsIndexRouteImport } from './routes/owner.teams.index'
import { Route as OwnerTeamsTeamIdRouteImport } from './routes/owner.teams.$teamId'
import { Route as OwnerToolsAccessResolutionRouteImport } from './routes/owner.tools.access-resolution'
import { Route as OwnerToolsApiTestRouteImport } from './routes/owner.tools.api-test'
import { Route as OwnerUsersIndexRouteImport } from './routes/owner.users.index'
import { Route as OwnerUsersUserIdRouteImport } from './routes/owner.users.$userId'
import { Route as OwnerPlansSubscriptionsIndexRouteImport } from './routes/owner.plans.subscriptions.index'
import { Route as OwnerPlansSubscriptionsSubscriptionIdRouteImport } from './routes/owner.plans.subscriptions.$subscriptionId'
import { Route as OwnerTeamsTeamIdIndexRouteImport } from './routes/owner.teams.$teamId.index'
import { Route as OwnerUsersUserIdIndexRouteImport } from './routes/owner.users.$userId.index'
import { Route as OwnerUsersUserIdRequestHistoryRouteImport } from './routes/owner.users.$userId.request-history'
import { Route as OwnerUsersUserIdApiKeysKeyIdRouteImport } from './routes/owner.users.$userId.api-keys.$keyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAccessPointsRoute = OwnerAccessPointsRouteImport.update({
  id: '/access-points',
  path: '/access-points',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAuditLogsRoute = OwnerAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAuthorityProductsRoute = OwnerAuthorityProductsRouteImport.update({
  id: '/authority-products',
  path: '/authority-products',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBudgetManagersRoute = OwnerBudgetManagersRouteImport.update({
  id: '/budget-managers',
  path: '/budget-managers',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBudgetPoliciesRoute = OwnerBudgetPoliciesRouteImport.update({
  id: '/budget-policies',
  path: '/budget-policies',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCreditsRoute = OwnerCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerKeysRoute = OwnerKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPlansRoute = OwnerPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPricingRoute = OwnerPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerProvidersRoute = OwnerProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRequestLogsRoute = OwnerRequestLogsRouteImport.update({
  id: '/request-logs',
  path: '/request-logs',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSystemSettingsRoute = OwnerSystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTeamsRoute = OwnerTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerUsersRoute = OwnerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAccountSecurityRoute = OwnerAccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOperationsCardActivationsRoute =
  OwnerOperationsCardActivationsRouteImport.update({
    id: '/operations/card-activations',
    path: '/operations/card-activations',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerOperationsGrantsRoute = OwnerOperationsGrantsRouteImport.update({
  id: '/operations/grants',
  path: '/operations/grants',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPlansAndBudgetsBudgetPoliciesRoute =
  OwnerPlansAndBudgetsBudgetPoliciesRouteImport.update({
    id: '/plans-and-budgets/budget-policies',
    path: '/plans-and-budgets/budget-policies',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerPlansAndBudgetsGovernanceBudgetsRoute =
  OwnerPlansAndBudgetsGovernanceBudgetsRouteImport.update({
    id: '/plans-and-budgets/governance-budgets',
    path: '/plans-and-budgets/governance-budgets',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerPlansAndBudgetsPlanPurchasesRoute =
  OwnerPlansAndBudgetsPlanPurchasesRouteImport.update({
    id: '/plans-and-budgets/plan-purchases',
    path: '/plans-and-budgets/plan-purchases',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerPlansAndBudgetsPlansRoute =
  OwnerPlansAndBudgetsPlansRouteImport.update({
    id: '/plans-and-budgets/plans',
    path: '/plans-and-budgets/plans',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerPlansIndexRoute = OwnerPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerPlansRoute,
} as any)
const OwnerPlansSubscriptionsRoute = OwnerPlansSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => OwnerPlansRoute,
} as any)
const OwnerTeamsIndexRoute = OwnerTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerTeamsRoute,
} as any)
const OwnerTeamsTeamIdRoute = OwnerTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => OwnerTeamsRoute,
} as any)
const OwnerToolsAccessResolutionRoute =
  OwnerToolsAccessResolutionRouteImport.update({
    id: '/tools/access-resolution',
    path: '/tools/access-resolution',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerToolsApiTestRoute = OwnerToolsApiTestRouteImport.update({
  id: '/tools/api-test',
  path: '/tools/api-test',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerUsersIndexRoute = OwnerUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerUsersRoute,
} as any)
const OwnerUsersUserIdRoute = OwnerUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => OwnerUsersRoute,
} as any)
const OwnerPlansSubscriptionsIndexRoute =
  OwnerPlansSubscriptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OwnerPlansSubscriptionsRoute,
  } as any)
const OwnerPlansSubscriptionsSubscriptionIdRoute =
  OwnerPlansSubscriptionsSubscriptionIdRouteImport.update({
    id: '/$subscriptionId',
    path: '/$subscriptionId',
    getParentRoute: () => OwnerPlansSubscriptionsRoute,
  } as any)
const OwnerTeamsTeamIdIndexRoute = OwnerTeamsTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerTeamsTeamIdRoute,
} as any)
const OwnerUsersUserIdIndexRoute = OwnerUsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerUsersUserIdRoute,
} as any)
const OwnerUsersUserIdRequestHistoryRoute =
  OwnerUsersUserIdRequestHistoryRouteImport.update({
    id: '/request-history',
    path: '/request-history',
    getParentRoute: () => OwnerUsersUserIdRoute,
  } as any)
const OwnerUsersUserIdApiKeysKeyIdRoute =
  OwnerUsersUserIdApiKeysKeyIdRouteImport.update({
    id: '/api-keys/$keyId',
    path: '/api-keys/$keyId',
    getParentRoute: () => OwnerUsersUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/owner/access-points': typeof OwnerAccessPointsRoute
  '/owner/audit-logs': typeof OwnerAuditLogsRoute
  '/owner/authority-products': typeof OwnerAuthorityProductsRoute
  '/owner/budget-managers': typeof OwnerBudgetManagersRoute
  '/owner/budget-policies': typeof OwnerBudgetPoliciesRoute
  '/owner/credits': typeof OwnerCreditsRoute
  '/owner/keys': typeof OwnerKeysRoute
  '/owner/plans': typeof OwnerPlansRouteWithChildren
  '/owner/pricing': typeof OwnerPricingRoute
  '/owner/providers': typeof OwnerProvidersRoute
  '/owner/request-logs': typeof OwnerRequestLogsRoute
  '/owner/system-settings': typeof OwnerSystemSettingsRoute
  '/owner/teams': typeof OwnerTeamsRouteWithChildren
  '/owner/users': typeof OwnerUsersRouteWithChildren
  '/owner/': typeof OwnerIndexRoute
  '/owner/account/security': typeof OwnerAccountSecurityRoute
  '/owner/operations/card-activations': typeof OwnerOperationsCardActivationsRoute
  '/owner/operations/grants': typeof OwnerOperationsGrantsRoute
  '/owner/plans-and-budgets/budget-policies': typeof OwnerPlansAndBudgetsBudgetPoliciesRoute
  '/owner/plans-and-budgets/governance-budgets': typeof OwnerPlansAndBudgetsGovernanceBudgetsRoute
  '/owner/plans-and-budgets/plan-purchases': typeof OwnerPlansAndBudgetsPlanPurchasesRoute
  '/owner/plans-and-budgets/plans': typeof OwnerPlansAndBudgetsPlansRoute
  '/owner/plans/subscriptions': typeof OwnerPlansSubscriptionsRouteWithChildren
  '/owner/teams/$teamId': typeof OwnerTeamsTeamIdRouteWithChildren
  '/owner/tools/access-resolution': typeof OwnerToolsAccessResolutionRoute
  '/owner/tools/api-test': typeof OwnerToolsApiTestRoute
  '/owner/users/$userId': typeof OwnerUsersUserIdRouteWithChildren
  '/owner/plans/': typeof OwnerPlansIndexRoute
  '/owner/teams/': typeof OwnerTeamsIndexRoute
  '/owner/users/': typeof OwnerUsersIndexRoute
  '/owner/plans/subscriptions/$subscriptionId': typeof OwnerPlansSubscriptionsSubscriptionIdRoute
  '/owner/users/$userId/request-history': typeof OwnerUsersUserIdRequestHistoryRoute
  '/owner/plans/subscriptions/': typeof OwnerPlansSubscriptionsIndexRoute
  '/owner/teams/$teamId/': typeof OwnerTeamsTeamIdIndexRoute
  '/owner/users/$userId/': typeof OwnerUsersUserIdIndexRoute
  '/owner/users/$userId/api-keys/$keyId': typeof OwnerUsersUserIdApiKeysKeyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/owner/access-points': typeof OwnerAccessPointsRoute
  '/owner/audit-logs': typeof OwnerAuditLogsRoute
  '/owner/authority-products': typeof OwnerAuthorityProductsRoute
  '/owner/budget-managers': typeof OwnerBudgetManagersRoute
  '/owner/budget-policies': typeof OwnerBudgetPoliciesRoute
  '/owner/credits': typeof OwnerCreditsRoute
  '/owner/keys': typeof OwnerKeysRoute
  '/owner/pricing': typeof OwnerPricingRoute
  '/owner/providers': typeof OwnerProvidersRoute
  '/owner/request-logs': typeof OwnerRequestLogsRoute
  '/owner/system-settings': typeof OwnerSystemSettingsRoute
  '/owner': typeof OwnerIndexRoute
  '/owner/account/security': typeof OwnerAccountSecurityRoute
  '/owner/operations/card-activations': typeof OwnerOperationsCardActivationsRoute
  '/owner/operations/grants': typeof OwnerOperationsGrantsRoute
  '/owner/plans-and-budgets/budget-policies': typeof OwnerPlansAndBudgetsBudgetPoliciesRoute
  '/owner/plans-and-budgets/governance-budgets': typeof OwnerPlansAndBudgetsGovernanceBudgetsRoute
  '/owner/plans-and-budgets/plan-purchases': typeof OwnerPlansAndBudgetsPlanPurchasesRoute
  '/owner/plans-and-budgets/plans': typeof OwnerPlansAndBudgetsPlansRoute
  '/owner/tools/access-resolution': typeof OwnerToolsAccessResolutionRoute
  '/owner/tools/api-test': typeof OwnerToolsApiTestRoute
  '/owner/plans': typeof OwnerPlansIndexRoute
  '/owner/teams': typeof OwnerTeamsIndexRoute
  '/owner/users': typeof OwnerUsersIndexRoute
  '/owner/plans/subscriptions/$subscriptionId': typeof OwnerPlansSubscriptionsSubscriptionIdRoute
  '/owner/users/$userId/request-history': typeof OwnerUsersUserIdRequestHistoryRoute
  '/owner/plans/subscriptions': typeof OwnerPlansSubscriptionsIndexRoute
  '/owner/teams/$teamId': typeof OwnerTeamsTeamIdIndexRoute
  '/owner/users/$userId': typeof OwnerUsersUserIdIndexRoute
  '/owner/users/$userId/api-keys/$keyId': typeof OwnerUsersUserIdApiKeysKeyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/owner/access-points': typeof OwnerAccessPointsRoute
  '/owner/audit-logs': typeof OwnerAuditLogsRoute
  '/owner/authority-products': typeof OwnerAuthorityProductsRoute
  '/owner/budget-managers': typeof OwnerBudgetManagersRoute
  '/owner/budget-policies': typeof OwnerBudgetPoliciesRoute
  '/owner/credits': typeof OwnerCreditsRoute
  '/owner/keys': typeof OwnerKeysRoute
  '/owner/plans': typeof OwnerPlansRouteWithChildren
  '/owner/pricing': typeof OwnerPricingRoute
  '/owner/providers': typeof OwnerProvidersRoute
  '/owner/request-logs': typeof OwnerRequestLogsRoute
  '/owner/system-settings': typeof OwnerSystemSettingsRoute
  '/owner/teams': typeof OwnerTeamsRouteWithChildren
  '/owner/users': typeof OwnerUsersRouteWithChildren
  '/owner/': typeof OwnerIndexRoute
  '/owner/account/security': typeof OwnerAccountSecurityRoute
  '/owner/operations/card-activations': typeof OwnerOperationsCardActivationsRoute
  '/owner/operations/grants': typeof OwnerOperationsGrantsRoute
  '/owner/plans-and-budgets/budget-policies': typeof OwnerPlansAndBudgetsBudgetPoliciesRoute
  '/owner/plans-and-budgets/governance-budgets': typeof OwnerPlansAndBudgetsGovernanceBudgetsRoute
  '/owner/plans-and-budgets/plan-purchases': typeof OwnerPlansAndBudgetsPlanPurchasesRoute
  '/owner/plans-and-budgets/plans': typeof OwnerPlansAndBudgetsPlansRoute
  '/owner/plans/subscriptions': typeof OwnerPlansSubscriptionsRouteWithChildren
  '/owner/teams/$teamId': typeof OwnerTeamsTeamIdRouteWithChildren
  '/owner/tools/access-resolution': typeof OwnerToolsAccessResolutionRoute
  '/owner/tools/api-test': typeof OwnerToolsApiTestRoute
  '/owner/users/$userId': typeof OwnerUsersUserIdRouteWithChildren
  '/owner/plans/': typeof OwnerPlansIndexRoute
  '/owner/teams/': typeof OwnerTeamsIndexRoute
  '/owner/users/': typeof OwnerUsersIndexRoute
  '/owner/plans/subscriptions/$subscriptionId': typeof OwnerPlansSubscriptionsSubscriptionIdRoute
  '/owner/users/$userId/request-history': typeof OwnerUsersUserIdRequestHistoryRoute
  '/owner/plans/subscriptions/': typeof OwnerPlansSubscriptionsIndexRoute
  '/owner/teams/$teamId/': typeof OwnerTeamsTeamIdIndexRoute
  '/owner/users/$userId/': typeof OwnerUsersUserIdIndexRoute
  '/owner/users/$userId/api-keys/$keyId': typeof OwnerUsersUserIdApiKeysKeyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner'
    | '/api/$'
    | '/owner/access-points'
    | '/owner/audit-logs'
    | '/owner/authority-products'
    | '/owner/budget-managers'
    | '/owner/budget-policies'
    | '/owner/credits'
    | '/owner/keys'
    | '/owner/plans'
    | '/owner/pricing'
    | '/owner/providers'
    | '/owner/request-logs'
    | '/owner/system-settings'
    | '/owner/teams'
    | '/owner/users'
    | '/owner/'
    | '/owner/account/security'
    | '/owner/operations/card-activations'
    | '/owner/operations/grants'
    | '/owner/plans-and-budgets/budget-policies'
    | '/owner/plans-and-budgets/governance-budgets'
    | '/owner/plans-and-budgets/plan-purchases'
    | '/owner/plans-and-budgets/plans'
    | '/owner/plans/subscriptions'
    | '/owner/teams/$teamId'
    | '/owner/tools/access-resolution'
    | '/owner/tools/api-test'
    | '/owner/users/$userId'
    | '/owner/plans/'
    | '/owner/teams/'
    | '/owner/users/'
    | '/owner/plans/subscriptions/$subscriptionId'
    | '/owner/users/$userId/request-history'
    | '/owner/plans/subscriptions/'
    | '/owner/teams/$teamId/'
    | '/owner/users/$userId/'
    | '/owner/users/$userId/api-keys/$keyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/owner/access-points'
    | '/owner/audit-logs'
    | '/owner/authority-products'
    | '/owner/budget-managers'
    | '/owner/budget-policies'
    | '/owner/credits'
    | '/owner/keys'
    | '/owner/pricing'
    | '/owner/providers'
    | '/owner/request-logs'
    | '/owner/system-settings'
    | '/owner'
    | '/owner/account/security'
    | '/owner/operations/card-activations'
    | '/owner/operations/grants'
    | '/owner/plans-and-budgets/budget-policies'
    | '/owner/plans-and-budgets/governance-budgets'
    | '/owner/plans-and-budgets/plan-purchases'
    | '/owner/plans-and-budgets/plans'
    | '/owner/tools/access-resolution'
    | '/owner/tools/api-test'
    | '/owner/plans'
    | '/owner/teams'
    | '/owner/users'
    | '/owner/plans/subscriptions/$subscriptionId'
    | '/owner/users/$userId/request-history'
    | '/owner/plans/subscriptions'
    | '/owner/teams/$teamId'
    | '/owner/users/$userId'
    | '/owner/users/$userId/api-keys/$keyId'
  id:
    | '__root__'
    | '/'
    | '/owner'
    | '/api/$'
    | '/owner/access-points'
    | '/owner/audit-logs'
    | '/owner/authority-products'
    | '/owner/budget-managers'
    | '/owner/budget-policies'
    | '/owner/credits'
    | '/owner/keys'
    | '/owner/plans'
    | '/owner/pricing'
    | '/owner/providers'
    | '/owner/request-logs'
    | '/owner/system-settings'
    | '/owner/teams'
    | '/owner/users'
    | '/owner/'
    | '/owner/account/security'
    | '/owner/operations/card-activations'
    | '/owner/operations/grants'
    | '/owner/plans-and-budgets/budget-policies'
    | '/owner/plans-and-budgets/governance-budgets'
    | '/owner/plans-and-budgets/plan-purchases'
    | '/owner/plans-and-budgets/plans'
    | '/owner/plans/subscriptions'
    | '/owner/teams/$teamId'
    | '/owner/tools/access-resolution'
    | '/owner/tools/api-test'
    | '/owner/users/$userId'
    | '/owner/plans/'
    | '/owner/teams/'
    | '/owner/users/'
    | '/owner/plans/subscriptions/$subscriptionId'
    | '/owner/users/$userId/request-history'
    | '/owner/plans/subscriptions/'
    | '/owner/teams/$teamId/'
    | '/owner/users/$userId/'
    | '/owner/users/$userId/api-keys/$keyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/access-points': {
      id: '/owner/access-points'
      path: '/access-points'
      fullPath: '/owner/access-points'
      preLoaderRoute: typeof OwnerAccessPointsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/audit-logs': {
      id: '/owner/audit-logs'
      path: '/audit-logs'
      fullPath: '/owner/audit-logs'
      preLoaderRoute: typeof OwnerAuditLogsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/authority-products': {
      id: '/owner/authority-products'
      path: '/authority-products'
      fullPath: '/owner/authority-products'
      preLoaderRoute: typeof OwnerAuthorityProductsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/budget-managers': {
      id: '/owner/budget-managers'
      path: '/budget-managers'
      fullPath: '/owner/budget-managers'
      preLoaderRoute: typeof OwnerBudgetManagersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/budget-policies': {
      id: '/owner/budget-policies'
      path: '/budget-policies'
      fullPath: '/owner/budget-policies'
      preLoaderRoute: typeof OwnerBudgetPoliciesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/credits': {
      id: '/owner/credits'
      path: '/credits'
      fullPath: '/owner/credits'
      preLoaderRoute: typeof OwnerCreditsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/keys': {
      id: '/owner/keys'
      path: '/keys'
      fullPath: '/owner/keys'
      preLoaderRoute: typeof OwnerKeysRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/plans': {
      id: '/owner/plans'
      path: '/plans'
      fullPath: '/owner/plans'
      preLoaderRoute: typeof OwnerPlansRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/pricing': {
      id: '/owner/pricing'
      path: '/pricing'
      fullPath: '/owner/pricing'
      preLoaderRoute: typeof OwnerPricingRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/providers': {
      id: '/owner/providers'
      path: '/providers'
      fullPath: '/owner/providers'
      preLoaderRoute: typeof OwnerProvidersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/request-logs': {
      id: '/owner/request-logs'
      path: '/request-logs'
      fullPath: '/owner/request-logs'
      preLoaderRoute: typeof OwnerRequestLogsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/system-settings': {
      id: '/owner/system-settings'
      path: '/system-settings'
      fullPath: '/owner/system-settings'
      preLoaderRoute: typeof OwnerSystemSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/teams': {
      id: '/owner/teams'
      path: '/teams'
      fullPath: '/owner/teams'
      preLoaderRoute: typeof OwnerTeamsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/users': {
      id: '/owner/users'
      path: '/users'
      fullPath: '/owner/users'
      preLoaderRoute: typeof OwnerUsersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/account/security': {
      id: '/owner/account/security'
      path: '/account/security'
      fullPath: '/owner/account/security'
      preLoaderRoute: typeof OwnerAccountSecurityRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/operations/card-activations': {
      id: '/owner/operations/card-activations'
      path: '/operations/card-activations'
      fullPath: '/owner/operations/card-activations'
      preLoaderRoute: typeof OwnerOperationsCardActivationsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/operations/grants': {
      id: '/owner/operations/grants'
      path: '/operations/grants'
      fullPath: '/owner/operations/grants'
      preLoaderRoute: typeof OwnerOperationsGrantsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/plans-and-budgets/budget-policies': {
      id: '/owner/plans-and-budgets/budget-policies'
      path: '/plans-and-budgets/budget-policies'
      fullPath: '/owner/plans-and-budgets/budget-policies'
      preLoaderRoute: typeof OwnerPlansAndBudgetsBudgetPoliciesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/plans-and-budgets/governance-budgets': {
      id: '/owner/plans-and-budgets/governance-budgets'
      path: '/plans-and-budgets/governance-budgets'
      fullPath: '/owner/plans-and-budgets/governance-budgets'
      preLoaderRoute: typeof OwnerPlansAndBudgetsGovernanceBudgetsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/plans-and-budgets/plan-purchases': {
      id: '/owner/plans-and-budgets/plan-purchases'
      path: '/plans-and-budgets/plan-purchases'
      fullPath: '/owner/plans-and-budgets/plan-purchases'
      preLoaderRoute: typeof OwnerPlansAndBudgetsPlanPurchasesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/plans-and-budgets/plans': {
      id: '/owner/plans-and-budgets/plans'
      path: '/plans-and-budgets/plans'
      fullPath: '/owner/plans-and-budgets/plans'
      preLoaderRoute: typeof OwnerPlansAndBudgetsPlansRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/plans/': {
      id: '/owner/plans/'
      path: '/'
      fullPath: '/owner/plans/'
      preLoaderRoute: typeof OwnerPlansIndexRouteImport
      parentRoute: typeof OwnerPlansRoute
    }
    '/owner/plans/subscriptions': {
      id: '/owner/plans/subscriptions'
      path: '/subscriptions'
      fullPath: '/owner/plans/subscriptions'
      preLoaderRoute: typeof OwnerPlansSubscriptionsRouteImport
      parentRoute: typeof OwnerPlansRoute
    }
    '/owner/teams/': {
      id: '/owner/teams/'
      path: '/'
      fullPath: '/owner/teams/'
      preLoaderRoute: typeof OwnerTeamsIndexRouteImport
      parentRoute: typeof OwnerTeamsRoute
    }
    '/owner/teams/$teamId': {
      id: '/owner/teams/$teamId'
      path: '/$teamId'
      fullPath: '/owner/teams/$teamId'
      preLoaderRoute: typeof OwnerTeamsTeamIdRouteImport
      parentRoute: typeof OwnerTeamsRoute
    }
    '/owner/tools/access-resolution': {
      id: '/owner/tools/access-resolution'
      path: '/tools/access-resolution'
      fullPath: '/owner/tools/access-resolution'
      preLoaderRoute: typeof OwnerToolsAccessResolutionRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/tools/api-test': {
      id: '/owner/tools/api-test'
      path: '/tools/api-test'
      fullPath: '/owner/tools/api-test'
      preLoaderRoute: typeof OwnerToolsApiTestRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/users/': {
      id: '/owner/users/'
      path: '/'
      fullPath: '/owner/users/'
      preLoaderRoute: typeof OwnerUsersIndexRouteImport
      parentRoute: typeof OwnerUsersRoute
    }
    '/owner/users/$userId': {
      id: '/owner/users/$userId'
      path: '/$userId'
      fullPath: '/owner/users/$userId'
      preLoaderRoute: typeof OwnerUsersUserIdRouteImport
      parentRoute: typeof OwnerUsersRoute
    }
    '/owner/plans/subscriptions/': {
      id: '/owner/plans/subscriptions/'
      path: '/'
      fullPath: '/owner/plans/subscriptions/'
      preLoaderRoute: typeof OwnerPlansSubscriptionsIndexRouteImport
      parentRoute: typeof OwnerPlansSubscriptionsRoute
    }
    '/owner/plans/subscriptions/$subscriptionId': {
      id: '/owner/plans/subscriptions/$subscriptionId'
      path: '/$subscriptionId'
      fullPath: '/owner/plans/subscriptions/$subscriptionId'
      preLoaderRoute: typeof OwnerPlansSubscriptionsSubscriptionIdRouteImport
      parentRoute: typeof OwnerPlansSubscriptionsRoute
    }
    '/owner/teams/$teamId/': {
      id: '/owner/teams/$teamId/'
      path: '/'
      fullPath: '/owner/teams/$teamId/'
      preLoaderRoute: typeof OwnerTeamsTeamIdIndexRouteImport
      parentRoute: typeof OwnerTeamsTeamIdRoute
    }
    '/owner/users/$userId/': {
      id: '/owner/users/$userId/'
      path: '/'
      fullPath: '/owner/users/$userId/'
      preLoaderRoute: typeof OwnerUsersUserIdIndexRouteImport
      parentRoute: typeof OwnerUsersUserIdRoute
    }
    '/owner/users/$userId/request-history': {
      id: '/owner/users/$userId/request-history'
      path: '/request-history'
      fullPath: '/owner/users/$userId/request-history'
      preLoaderRoute: typeof OwnerUsersUserIdRequestHistoryRouteImport
      parentRoute: typeof OwnerUsersUserIdRoute
    }
    '/owner/users/$userId/api-keys/$keyId': {
      id: '/owner/users/$userId/api-keys/$keyId'
      path: '/api-keys/$keyId'
      fullPath: '/owner/users/$userId/api-keys/$keyId'
      preLoaderRoute: typeof OwnerUsersUserIdApiKeysKeyIdRouteImport
      parentRoute: typeof OwnerUsersUserIdRoute
    }
  }
}

interface OwnerPlansSubscriptionsRouteChildren {
  OwnerPlansSubscriptionsSubscriptionIdRoute: typeof OwnerPlansSubscriptionsSubscriptionIdRoute
  OwnerPlansSubscriptionsIndexRoute: typeof OwnerPlansSubscriptionsIndexRoute
}

const OwnerPlansSubscriptionsRouteChildren: OwnerPlansSubscriptionsRouteChildren =
  {
    OwnerPlansSubscriptionsSubscriptionIdRoute:
      OwnerPlansSubscriptionsSubscriptionIdRoute,
    OwnerPlansSubscriptionsIndexRoute: OwnerPlansSubscriptionsIndexRoute,
  }

const OwnerPlansSubscriptionsRouteWithChildren =
  OwnerPlansSubscriptionsRoute._addFileChildren(
    OwnerPlansSubscriptionsRouteChildren,
  )

interface OwnerPlansRouteChildren {
  OwnerPlansSubscriptionsRoute: typeof OwnerPlansSubscriptionsRouteWithChildren
  OwnerPlansIndexRoute: typeof OwnerPlansIndexRoute
}

const OwnerPlansRouteChildren: OwnerPlansRouteChildren = {
  OwnerPlansSubscriptionsRoute: OwnerPlansSubscriptionsRouteWithChildren,
  OwnerPlansIndexRoute: OwnerPlansIndexRoute,
}

const OwnerPlansRouteWithChildren = OwnerPlansRoute._addFileChildren(
  OwnerPlansRouteChildren,
)

interface OwnerTeamsTeamIdRouteChildren {
  OwnerTeamsTeamIdIndexRoute: typeof OwnerTeamsTeamIdIndexRoute
}

const OwnerTeamsTeamIdRouteChildren: OwnerTeamsTeamIdRouteChildren = {
  OwnerTeamsTeamIdIndexRoute: OwnerTeamsTeamIdIndexRoute,
}

const OwnerTeamsTeamIdRouteWithChildren =
  OwnerTeamsTeamIdRoute._addFileChildren(OwnerTeamsTeamIdRouteChildren)

interface OwnerTeamsRouteChildren {
  OwnerTeamsTeamIdRoute: typeof OwnerTeamsTeamIdRouteWithChildren
  OwnerTeamsIndexRoute: typeof OwnerTeamsIndexRoute
}

const OwnerTeamsRouteChildren: OwnerTeamsRouteChildren = {
  OwnerTeamsTeamIdRoute: OwnerTeamsTeamIdRouteWithChildren,
  OwnerTeamsIndexRoute: OwnerTeamsIndexRoute,
}

const OwnerTeamsRouteWithChildren = OwnerTeamsRoute._addFileChildren(
  OwnerTeamsRouteChildren,
)

interface OwnerUsersUserIdRouteChildren {
  OwnerUsersUserIdRequestHistoryRoute: typeof OwnerUsersUserIdRequestHistoryRoute
  OwnerUsersUserIdIndexRoute: typeof OwnerUsersUserIdIndexRoute
  OwnerUsersUserIdApiKeysKeyIdRoute: typeof OwnerUsersUserIdApiKeysKeyIdRoute
}

const OwnerUsersUserIdRouteChildren: OwnerUsersUserIdRouteChildren = {
  OwnerUsersUserIdRequestHistoryRoute: OwnerUsersUserIdRequestHistoryRoute,
  OwnerUsersUserIdIndexRoute: OwnerUsersUserIdIndexRoute,
  OwnerUsersUserIdApiKeysKeyIdRoute: OwnerUsersUserIdApiKeysKeyIdRoute,
}

const OwnerUsersUserIdRouteWithChildren =
  OwnerUsersUserIdRoute._addFileChildren(OwnerUsersUserIdRouteChildren)

interface OwnerUsersRouteChildren {
  OwnerUsersUserIdRoute: typeof OwnerUsersUserIdRouteWithChildren
  OwnerUsersIndexRoute: typeof OwnerUsersIndexRoute
}

const OwnerUsersRouteChildren: OwnerUsersRouteChildren = {
  OwnerUsersUserIdRoute: OwnerUsersUserIdRouteWithChildren,
  OwnerUsersIndexRoute: OwnerUsersIndexRoute,
}

const OwnerUsersRouteWithChildren = OwnerUsersRoute._addFileChildren(
  OwnerUsersRouteChildren,
)

interface OwnerRouteChildren {
  OwnerAccessPointsRoute: typeof OwnerAccessPointsRoute
  OwnerAuditLogsRoute: typeof OwnerAuditLogsRoute
  OwnerAuthorityProductsRoute: typeof OwnerAuthorityProductsRoute
  OwnerBudgetManagersRoute: typeof OwnerBudgetManagersRoute
  OwnerBudgetPoliciesRoute: typeof OwnerBudgetPoliciesRoute
  OwnerCreditsRoute: typeof OwnerCreditsRoute
  OwnerKeysRoute: typeof OwnerKeysRoute
  OwnerPlansRoute: typeof OwnerPlansRouteWithChildren
  OwnerPricingRoute: typeof OwnerPricingRoute
  OwnerProvidersRoute: typeof OwnerProvidersRoute
  OwnerRequestLogsRoute: typeof OwnerRequestLogsRoute
  OwnerSystemSettingsRoute: typeof OwnerSystemSettingsRoute
  OwnerTeamsRoute: typeof OwnerTeamsRouteWithChildren
  OwnerUsersRoute: typeof OwnerUsersRouteWithChildren
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerAccountSecurityRoute: typeof OwnerAccountSecurityRoute
  OwnerOperationsCardActivationsRoute: typeof OwnerOperationsCardActivationsRoute
  OwnerOperationsGrantsRoute: typeof OwnerOperationsGrantsRoute
  OwnerPlansAndBudgetsBudgetPoliciesRoute: typeof OwnerPlansAndBudgetsBudgetPoliciesRoute
  OwnerPlansAndBudgetsGovernanceBudgetsRoute: typeof OwnerPlansAndBudgetsGovernanceBudgetsRoute
  OwnerPlansAndBudgetsPlanPurchasesRoute: typeof OwnerPlansAndBudgetsPlanPurchasesRoute
  OwnerPlansAndBudgetsPlansRoute: typeof OwnerPlansAndBudgetsPlansRoute
  OwnerToolsAccessResolutionRoute: typeof OwnerToolsAccessResolutionRoute
  OwnerToolsApiTestRoute: typeof OwnerToolsApiTestRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAccessPointsRoute: OwnerAccessPointsRoute,
  OwnerAuditLogsRoute: OwnerAuditLogsRoute,
  OwnerAuthorityProductsRoute: OwnerAuthorityProductsRoute,
  OwnerBudgetManagersRoute: OwnerBudgetManagersRoute,
  OwnerBudgetPoliciesRoute: OwnerBudgetPoliciesRoute,
  OwnerCreditsRoute: OwnerCreditsRoute,
  OwnerKeysRoute: OwnerKeysRoute,
  OwnerPlansRoute: OwnerPlansRouteWithChildren,
  OwnerPricingRoute: OwnerPricingRoute,
  OwnerProvidersRoute: OwnerProvidersRoute,
  OwnerRequestLogsRoute: OwnerRequestLogsRoute,
  OwnerSystemSettingsRoute: OwnerSystemSettingsRoute,
  OwnerTeamsRoute: OwnerTeamsRouteWithChildren,
  OwnerUsersRoute: OwnerUsersRouteWithChildren,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerAccountSecurityRoute: OwnerAccountSecurityRoute,
  OwnerOperationsCardActivationsRoute: OwnerOperationsCardActivationsRoute,
  OwnerOperationsGrantsRoute: OwnerOperationsGrantsRoute,
  OwnerPlansAndBudgetsBudgetPoliciesRoute:
    OwnerPlansAndBudgetsBudgetPoliciesRoute,
  OwnerPlansAndBudgetsGovernanceBudgetsRoute:
    OwnerPlansAndBudgetsGovernanceBudgetsRoute,
  OwnerPlansAndBudgetsPlanPurchasesRoute:
    OwnerPlansAndBudgetsPlanPurchasesRoute,
  OwnerPlansAndBudgetsPlansRoute: OwnerPlansAndBudgetsPlansRoute,
  OwnerToolsAccessResolutionRoute: OwnerToolsAccessResolutionRoute,
  OwnerToolsApiTestRoute: OwnerToolsApiTestRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
