import { configDefaults, defineConfig } from "vitest/config";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL(".", import.meta.url));

export const workspaceSourceAliases = {
  "@admin/": `${root}apps/admin/src/`,
  "@web/": `${root}apps/web/src/`,
  "@frely/observability/generated-dialog-registry": `${root}packages/observability/src/generated-dialog-registry.ts`,
  "@frely/observability/gateway-metrics": `${root}packages/observability/src/gateway-metrics.ts`,
  "@frely/observability/client-runtime": `${root}packages/observability/src/client-runtime.ts`,
  "@frely/observability/instrumentation": `${root}packages/observability/src/instrumentation.ts`,
  "@frely/observability/contracts": `${root}packages/observability/src/contracts.ts`,
  "@frely/observability/server": `${root}packages/observability/src/server.ts`,
  "@frely/observability": `${root}packages/observability/src/index.ts`,
  "@frely/core": `${root}packages/core/src/index.ts`,
  "@frely/audit/application-internal": `${root}packages/audit/src/application-internal.ts`,
  "@frely/audit/server": `${root}packages/audit/src/public-server.ts`,
  "@frely/audit": `${root}packages/audit/src/index.ts`,
  "@frely/authority/application-internal": `${root}packages/authority/src/application-internal.ts`,
  "@frely/authority/server": `${root}packages/authority/src/public-server.ts`,
  "@frely/authority": `${root}packages/authority/src/index.ts`,
  "@frely/config/workspace": `${root}packages/config/src/workspace.ts`,
  "@frely/config": `${root}packages/config/src/index.ts`,
  "@frely/db-ops": `${root}packages/db-ops/src/index.ts`,
  "@frely/capture": `${root}packages/capture/src/index.ts`,
  "@frely/application/runtime": `${root}packages/application/src/storage/runtime.ts`,
  "@frely/entitlement/application-internal": `${root}packages/entitlement/src/application-internal.ts`,
  "@frely/entitlement/server": `${root}packages/entitlement/src/public-server.ts`,
  "@frely/entitlement": `${root}packages/entitlement/src/index.ts`,
  "@frely/billing/application-internal": `${root}packages/billing/src/application-internal.ts`,
  "@frely/billing/server": `${root}packages/billing/src/public-server.ts`,
  "@frely/billing": `${root}packages/billing/src/index.ts`,
  "@frely/application/server": `${root}packages/application/src/public-server.ts`,
  "@frely/application/application-internal": `${root}packages/application/src/application-internal.ts`,
  "@frely/application/internal/verification": `${root}packages/application/src/internal-verification.ts`,
  "@frely/application/internal/operations": `${root}packages/application/src/internal-operations.ts`,
  "@frely/application": `${root}packages/application/src/index.ts`,
  "@frely/application-operations": `${root}packages/application-operations/src/index.ts`,
  "@frely/ui-application/contracts": `${root}packages/ui-application/src/contracts.ts`,
  "@frely/ui-application/server": `${root}packages/ui-application/src/server.ts`,
  "@frely/model-access/types": `${root}packages/model-access/src/types.ts`,
  "@frely/model-access/routing-runtime": `${root}packages/model-access/src/routing-runtime.ts`,
  "@frely/model-access/server": `${root}packages/model-access/src/public-server.ts`,
  "@frely/model-access/application-internal": `${root}packages/model-access/src/application-internal.ts`,
  "@frely/model-access": `${root}packages/model-access/src/index.ts`,
  "@frely/postgres/instance-data-profile": `${root}packages/postgres/src/instance-data-profile.ts`,
  "@frely/postgres/migration-state": `${root}packages/postgres/src/migration-state.ts`,
  "@frely/postgres/model-types": `${root}packages/postgres/src/model-types.ts`,
  "@frely/postgres/runtime-artifacts": `${root}packages/postgres/src/runtime-artifacts.ts`,
  "@frely/postgres/server": `${root}packages/postgres/src/server.ts`,
  "@frely/postgres": `${root}packages/postgres/src/index.ts`,
  "@frely/pi-tunnel": `${root}packages/pi-tunnel/src/index.ts`,
  "@frely/provider-runtime/server": `${root}packages/provider-runtime/src/server.ts`,
  "@frely/provider-runtime/adapter": `${root}packages/provider-runtime/src/adapter.ts`,
  "@frely/provider-runtime": `${root}packages/provider-runtime/src/index.ts`,
  "@frely/request-execution/application-internal": `${root}packages/request-execution/src/application-internal.ts`,
  "@frely/request-execution/server": `${root}packages/request-execution/src/public-server.ts`,
  "@frely/request-execution": `${root}packages/request-execution/src/index.ts`,
  "@frely/auth/password-policy": `${root}packages/auth/src/password-policy.ts`,
  "@frely/auth": `${root}packages/auth/src/index.ts`,
  "@frely/identity/application-internal": `${root}packages/identity/src/application-internal.ts`,
  "@frely/identity/server": `${root}packages/identity/src/public-server.ts`,
  "@frely/identity": `${root}packages/identity/src/index.ts`,
  "@frely/tenancy-context/application-internal": `${root}packages/tenancy-context/src/application-internal.ts`,
  "@frely/tenancy-context/server": `${root}packages/tenancy-context/src/public-server.ts`,
  "@frely/tenancy-context": `${root}packages/tenancy-context/src/index.ts`,
  "@frely/tenancy/audience-server": `${root}packages/tenancy/src/audience-server.ts`,
  "@frely/tenancy/server": `${root}packages/tenancy/src/server.ts`,
  "@frely/tenancy": `${root}packages/tenancy/src/index.ts`,
  "@frely/gateway-core": `${root}packages/gateway/src/index.ts`,
  "@frely/hub": `${root}apps/hub/src/index.ts`,
  "@frely/providers/credentials": `${root}packages/providers/src/provider-credentials.ts`,
  "@frely/providers": `${root}packages/providers/src/index.ts`,
  "@frely/pricing": `${root}packages/pricing/src/index.ts`,
  "@frely/ui/components/": `${root}packages/ui/src/components/`,
  "@frely/ui/components": `${root}packages/ui/src/components`,
  "@frely/ui/lib/": `${root}packages/ui/src/lib/`,
  "@frely/ui/lib": `${root}packages/ui/src/lib`,
  "@frely/ui": `${root}packages/ui/src/index.ts`,
  "@frely/console-ui/client": `${root}packages/console-ui/src/client.ts`,
  "@frely/console-ui/models": `${root}packages/console-ui/src/models.ts`,
  "@frely/console-ui/messages": `${root}packages/console-ui/src/messages.ts`,
  "@frely/console-ui/": `${root}packages/console-ui/src/`,
  "@frely/console-ui": `${root}packages/console-ui/src/index.tsx`,
  "@frely/team-console-ui/client": `${root}packages/team-console-ui/src/client.ts`,
  "@frely/team-console-ui/models": `${root}packages/team-console-ui/src/models.ts`,
  "@frely/team-console-ui": `${root}packages/team-console-ui/src/index.tsx`,
  "@frely/testkit": `${root}packages/testkit/src/index.ts`,
} as const;

export const focusedTestMaxWorkers = 1;

export default defineConfig({
  resolve: {
    alias: {
      ...workspaceSourceAliases,
      "server-only": `${root}tests/server-only.ts`
    }
  },
  test: {
    maxWorkers: focusedTestMaxWorkers,
    testTimeout: 30_000,
    include: ["tests/**/*.test.{ts,tsx}", "apps/**/*.test.{ts,tsx}", "packages/**/*.test.{ts,tsx}"],
    exclude: [...configDefaults.exclude, "**/.next/**"],
    globals: true,
    environment: "node"
  }
});
