/* Generated by scripts/generate-ui-surface-registries.mjs. Do not edit. */
import { createRouteRegistry } from "@frely/observability/contracts";

export const routeNames = [
  "/",
  "/owner",
  "/owner/access-points",
  "/owner/account/security",
  "/owner/audit-logs",
  "/owner/authority-products",
  "/owner/budget-managers",
  "/owner/budget-policies",
  "/owner/credits",
  "/owner/keys",
  "/owner/operations/card-activations",
  "/owner/operations/grants",
  "/owner/plans",
  "/owner/plans-and-budgets/budget-policies",
  "/owner/plans-and-budgets/governance-budgets",
  "/owner/plans-and-budgets/plan-purchases",
  "/owner/plans-and-budgets/plans",
  "/owner/plans/subscriptions",
  "/owner/plans/subscriptions/[subscriptionId]",
  "/owner/pricing",
  "/owner/providers",
  "/owner/request-logs",
  "/owner/system-settings",
  "/owner/teams",
  "/owner/teams/[teamId]",
  "/owner/tools/access-resolution",
  "/owner/tools/api-test",
  "/owner/users",
  "/owner/users/[userId]",
  "/owner/users/[userId]/api-keys/[keyId]",
  "/owner/users/[userId]/request-history"
] as const;
export const routeRegistry = createRouteRegistry(routeNames);
