/* Generated by scripts/generate-ui-surface-registries.mjs. Do not edit. */
import { createRouteRegistry } from "@frely/observability/contracts";

export const routeNames = [
  "/",
  "/key",
  "/login",
  "/register",
  "/user",
  "/user/[userId]",
  "/user/access",
  "/user/access/access-points",
  "/user/access/available-models",
  "/user/access/order",
  "/user/account",
  "/user/account/security",
  "/user/api-keys",
  "/user/authority",
  "/user/cards",
  "/user/chat",
  "/user/credits",
  "/user/keys",
  "/user/keys/[keyId]",
  "/user/plans-and-budgets",
  "/user/plans-and-budgets/budget",
  "/user/plans-and-budgets/plans",
  "/user/request-history",
  "/user/team",
  "/user/team/[teamId]",
  "/user/team/[teamId]/usage",
  "/user/tools",
  "/user/tools/api-test"
] as const;
export const routeRegistry = createRouteRegistry(routeNames);
