/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeyRouteImport } from './routes/key'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as UserRouteImport } from './routes/user'
import { Route as Char91DotwellKnownChar93OpenidConfigurationRouteImport } from './routes/[.well-known].openid-configuration'
import { Route as ActivateCardRouteImport } from './routes/activate.card'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthLandingEntryRouteImport } from './routes/auth.landing-entry'
import { Route as OidcAuthorizeRouteImport } from './routes/oidc.authorize'
import { Route as OidcJwksRouteImport } from './routes/oidc.jwks'
import { Route as OidcRevokeRouteImport } from './routes/oidc.revoke'
import { Route as OidcTokenRouteImport } from './routes/oidc.token'
import { Route as OidcUserinfoRouteImport } from './routes/oidc.userinfo'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as UserUserIdRouteImport } from './routes/user.$userId'
import { Route as UserAccessRouteImport } from './routes/user.access'
import { Route as UserAccountRouteImport } from './routes/user.account'
import { Route as UserApiKeysRouteImport } from './routes/user.api-keys'
import { Route as UserAuthorityRouteImport } from './routes/user.authority'
import { Route as UserCardsRouteImport } from './routes/user.cards'
import { Route as UserChatRouteImport } from './routes/user.chat'
import { Route as UserCreditsRouteImport } from './routes/user.credits'
import { Route as UserKeysRouteImport } from './routes/user.keys'
import { Route as UserPlansAndBudgetsRouteImport } from './routes/user.plans-and-budgets'
import { Route as UserRequestHistoryRouteImport } from './routes/user.request-history'
import { Route as UserTeamRouteImport } from './routes/user.team'
import { Route as UserToolsRouteImport } from './routes/user.tools'
import { Route as UserAccessAccessPointsRouteImport } from './routes/user.access.access-points'
import { Route as UserAccessAvailableModelsRouteImport } from './routes/user.access.available-models'
import { Route as UserAccessOrderRouteImport } from './routes/user.access.order'
import { Route as UserAccountIndexRouteImport } from './routes/user.account.index'
import { Route as UserAccountSecurityRouteImport } from './routes/user.account.security'
import { Route as UserKeysIndexRouteImport } from './routes/user.keys.index'
import { Route as UserKeysKeyIdRouteImport } from './routes/user.keys.$keyId'
import { Route as UserPlansAndBudgetsBudgetRouteImport } from './routes/user.plans-and-budgets.budget'
import { Route as UserPlansAndBudgetsPlansRouteImport } from './routes/user.plans-and-budgets.plans'
import { Route as UserTeamIndexRouteImport } from './routes/user.team.index'
import { Route as UserTeamTeamIdRouteImport } from './routes/user.team.$teamId'
import { Route as UserToolsApiTestRouteImport } from './routes/user.tools.api-test'
import { Route as UserTeamTeamIdIndexRouteImport } from './routes/user.team.$teamId.index'
import { Route as UserTeamTeamIdUsageRouteImport } from './routes/user.team.$teamId.usage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyRoute = KeyRouteImport.update({
  id: '/key',
  path: '/key',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OpenidConfigurationRoute =
  Char91DotwellKnownChar93OpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActivateCardRoute = ActivateCardRouteImport.update({
  id: '/activate/card',
  path: '/activate/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLandingEntryRoute = AuthLandingEntryRouteImport.update({
  id: '/auth/landing-entry',
  path: '/auth/landing-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcAuthorizeRoute = OidcAuthorizeRouteImport.update({
  id: '/oidc/authorize',
  path: '/oidc/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcJwksRoute = OidcJwksRouteImport.update({
  id: '/oidc/jwks',
  path: '/oidc/jwks',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcRevokeRoute = OidcRevokeRouteImport.update({
  id: '/oidc/revoke',
  path: '/oidc/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcTokenRoute = OidcTokenRouteImport.update({
  id: '/oidc/token',
  path: '/oidc/token',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcUserinfoRoute = OidcUserinfoRouteImport.update({
  id: '/oidc/userinfo',
  path: '/oidc/userinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UserRoute,
} as any)
const UserAccessRoute = UserAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => UserRoute,
} as any)
const UserAccountRoute = UserAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => UserRoute,
} as any)
const UserApiKeysRoute = UserApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => UserRoute,
} as any)
const UserAuthorityRoute = UserAuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => UserRoute,
} as any)
const UserCardsRoute = UserCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => UserRoute,
} as any)
const UserChatRoute = UserChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => UserRoute,
} as any)
const UserCreditsRoute = UserCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => UserRoute,
} as any)
const UserKeysRoute = UserKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => UserRoute,
} as any)
const UserPlansAndBudgetsRoute = UserPlansAndBudgetsRouteImport.update({
  id: '/plans-and-budgets',
  path: '/plans-and-budgets',
  getParentRoute: () => UserRoute,
} as any)
const UserRequestHistoryRoute = UserRequestHistoryRouteImport.update({
  id: '/request-history',
  path: '/request-history',
  getParentRoute: () => UserRoute,
} as any)
const UserTeamRoute = UserTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => UserRoute,
} as any)
const UserToolsRoute = UserToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => UserRoute,
} as any)
const UserAccessAccessPointsRoute = UserAccessAccessPointsRouteImport.update({
  id: '/access-points',
  path: '/access-points',
  getParentRoute: () => UserAccessRoute,
} as any)
const UserAccessAvailableModelsRoute =
  UserAccessAvailableModelsRouteImport.update({
    id: '/available-models',
    path: '/available-models',
    getParentRoute: () => UserAccessRoute,
  } as any)
const UserAccessOrderRoute = UserAccessOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => UserAccessRoute,
} as any)
const UserAccountIndexRoute = UserAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserAccountRoute,
} as any)
const UserAccountSecurityRoute = UserAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => UserAccountRoute,
} as any)
const UserKeysIndexRoute = UserKeysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserKeysRoute,
} as any)
const UserKeysKeyIdRoute = UserKeysKeyIdRouteImport.update({
  id: '/$keyId',
  path: '/$keyId',
  getParentRoute: () => UserKeysRoute,
} as any)
const UserPlansAndBudgetsBudgetRoute =
  UserPlansAndBudgetsBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => UserPlansAndBudgetsRoute,
  } as any)
const UserPlansAndBudgetsPlansRoute =
  UserPlansAndBudgetsPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => UserPlansAndBudgetsRoute,
  } as any)
const UserTeamIndexRoute = UserTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserTeamRoute,
} as any)
const UserTeamTeamIdRoute = UserTeamTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => UserTeamRoute,
} as any)
const UserToolsApiTestRoute = UserToolsApiTestRouteImport.update({
  id: '/api-test',
  path: '/api-test',
  getParentRoute: () => UserToolsRoute,
} as any)
const UserTeamTeamIdIndexRoute = UserTeamTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserTeamTeamIdRoute,
} as any)
const UserTeamTeamIdUsageRoute = UserTeamTeamIdUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => UserTeamTeamIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/key': typeof KeyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/.well-known/openid-configuration': typeof Char91DotwellKnownChar93OpenidConfigurationRoute
  '/activate/card': typeof ActivateCardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/landing-entry': typeof AuthLandingEntryRoute
  '/oidc/authorize': typeof OidcAuthorizeRoute
  '/oidc/jwks': typeof OidcJwksRoute
  '/oidc/revoke': typeof OidcRevokeRoute
  '/oidc/token': typeof OidcTokenRoute
  '/oidc/userinfo': typeof OidcUserinfoRoute
  '/user/$userId': typeof UserUserIdRoute
  '/user/access': typeof UserAccessRouteWithChildren
  '/user/account': typeof UserAccountRouteWithChildren
  '/user/api-keys': typeof UserApiKeysRoute
  '/user/authority': typeof UserAuthorityRoute
  '/user/cards': typeof UserCardsRoute
  '/user/chat': typeof UserChatRoute
  '/user/credits': typeof UserCreditsRoute
  '/user/keys': typeof UserKeysRouteWithChildren
  '/user/plans-and-budgets': typeof UserPlansAndBudgetsRouteWithChildren
  '/user/request-history': typeof UserRequestHistoryRoute
  '/user/team': typeof UserTeamRouteWithChildren
  '/user/tools': typeof UserToolsRouteWithChildren
  '/user/': typeof UserIndexRoute
  '/user/access/access-points': typeof UserAccessAccessPointsRoute
  '/user/access/available-models': typeof UserAccessAvailableModelsRoute
  '/user/access/order': typeof UserAccessOrderRoute
  '/user/account/security': typeof UserAccountSecurityRoute
  '/user/keys/$keyId': typeof UserKeysKeyIdRoute
  '/user/plans-and-budgets/budget': typeof UserPlansAndBudgetsBudgetRoute
  '/user/plans-and-budgets/plans': typeof UserPlansAndBudgetsPlansRoute
  '/user/team/$teamId': typeof UserTeamTeamIdRouteWithChildren
  '/user/tools/api-test': typeof UserToolsApiTestRoute
  '/user/account/': typeof UserAccountIndexRoute
  '/user/keys/': typeof UserKeysIndexRoute
  '/user/team/': typeof UserTeamIndexRoute
  '/user/team/$teamId/usage': typeof UserTeamTeamIdUsageRoute
  '/user/team/$teamId/': typeof UserTeamTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/key': typeof KeyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/.well-known/openid-configuration': typeof Char91DotwellKnownChar93OpenidConfigurationRoute
  '/activate/card': typeof ActivateCardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/landing-entry': typeof AuthLandingEntryRoute
  '/oidc/authorize': typeof OidcAuthorizeRoute
  '/oidc/jwks': typeof OidcJwksRoute
  '/oidc/revoke': typeof OidcRevokeRoute
  '/oidc/token': typeof OidcTokenRoute
  '/oidc/userinfo': typeof OidcUserinfoRoute
  '/user/$userId': typeof UserUserIdRoute
  '/user/access': typeof UserAccessRouteWithChildren
  '/user/api-keys': typeof UserApiKeysRoute
  '/user/authority': typeof UserAuthorityRoute
  '/user/cards': typeof UserCardsRoute
  '/user/chat': typeof UserChatRoute
  '/user/credits': typeof UserCreditsRoute
  '/user/plans-and-budgets': typeof UserPlansAndBudgetsRouteWithChildren
  '/user/request-history': typeof UserRequestHistoryRoute
  '/user/tools': typeof UserToolsRouteWithChildren
  '/user': typeof UserIndexRoute
  '/user/access/access-points': typeof UserAccessAccessPointsRoute
  '/user/access/available-models': typeof UserAccessAvailableModelsRoute
  '/user/access/order': typeof UserAccessOrderRoute
  '/user/account/security': typeof UserAccountSecurityRoute
  '/user/keys/$keyId': typeof UserKeysKeyIdRoute
  '/user/plans-and-budgets/budget': typeof UserPlansAndBudgetsBudgetRoute
  '/user/plans-and-budgets/plans': typeof UserPlansAndBudgetsPlansRoute
  '/user/tools/api-test': typeof UserToolsApiTestRoute
  '/user/account': typeof UserAccountIndexRoute
  '/user/keys': typeof UserKeysIndexRoute
  '/user/team': typeof UserTeamIndexRoute
  '/user/team/$teamId/usage': typeof UserTeamTeamIdUsageRoute
  '/user/team/$teamId': typeof UserTeamTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/key': typeof KeyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/.well-known/openid-configuration': typeof Char91DotwellKnownChar93OpenidConfigurationRoute
  '/activate/card': typeof ActivateCardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/landing-entry': typeof AuthLandingEntryRoute
  '/oidc/authorize': typeof OidcAuthorizeRoute
  '/oidc/jwks': typeof OidcJwksRoute
  '/oidc/revoke': typeof OidcRevokeRoute
  '/oidc/token': typeof OidcTokenRoute
  '/oidc/userinfo': typeof OidcUserinfoRoute
  '/user/$userId': typeof UserUserIdRoute
  '/user/access': typeof UserAccessRouteWithChildren
  '/user/account': typeof UserAccountRouteWithChildren
  '/user/api-keys': typeof UserApiKeysRoute
  '/user/authority': typeof UserAuthorityRoute
  '/user/cards': typeof UserCardsRoute
  '/user/chat': typeof UserChatRoute
  '/user/credits': typeof UserCreditsRoute
  '/user/keys': typeof UserKeysRouteWithChildren
  '/user/plans-and-budgets': typeof UserPlansAndBudgetsRouteWithChildren
  '/user/request-history': typeof UserRequestHistoryRoute
  '/user/team': typeof UserTeamRouteWithChildren
  '/user/tools': typeof UserToolsRouteWithChildren
  '/user/': typeof UserIndexRoute
  '/user/access/access-points': typeof UserAccessAccessPointsRoute
  '/user/access/available-models': typeof UserAccessAvailableModelsRoute
  '/user/access/order': typeof UserAccessOrderRoute
  '/user/account/security': typeof UserAccountSecurityRoute
  '/user/keys/$keyId': typeof UserKeysKeyIdRoute
  '/user/plans-and-budgets/budget': typeof UserPlansAndBudgetsBudgetRoute
  '/user/plans-and-budgets/plans': typeof UserPlansAndBudgetsPlansRoute
  '/user/team/$teamId': typeof UserTeamTeamIdRouteWithChildren
  '/user/tools/api-test': typeof UserToolsApiTestRoute
  '/user/account/': typeof UserAccountIndexRoute
  '/user/keys/': typeof UserKeysIndexRoute
  '/user/team/': typeof UserTeamIndexRoute
  '/user/team/$teamId/usage': typeof UserTeamTeamIdUsageRoute
  '/user/team/$teamId/': typeof UserTeamTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/key'
    | '/login'
    | '/register'
    | '/user'
    | '/.well-known/openid-configuration'
    | '/activate/card'
    | '/api/$'
    | '/auth/landing-entry'
    | '/oidc/authorize'
    | '/oidc/jwks'
    | '/oidc/revoke'
    | '/oidc/token'
    | '/oidc/userinfo'
    | '/user/$userId'
    | '/user/access'
    | '/user/account'
    | '/user/api-keys'
    | '/user/authority'
    | '/user/cards'
    | '/user/chat'
    | '/user/credits'
    | '/user/keys'
    | '/user/plans-and-budgets'
    | '/user/request-history'
    | '/user/team'
    | '/user/tools'
    | '/user/'
    | '/user/access/access-points'
    | '/user/access/available-models'
    | '/user/access/order'
    | '/user/account/security'
    | '/user/keys/$keyId'
    | '/user/plans-and-budgets/budget'
    | '/user/plans-and-budgets/plans'
    | '/user/team/$teamId'
    | '/user/tools/api-test'
    | '/user/account/'
    | '/user/keys/'
    | '/user/team/'
    | '/user/team/$teamId/usage'
    | '/user/team/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/key'
    | '/login'
    | '/register'
    | '/.well-known/openid-configuration'
    | '/activate/card'
    | '/api/$'
    | '/auth/landing-entry'
    | '/oidc/authorize'
    | '/oidc/jwks'
    | '/oidc/revoke'
    | '/oidc/token'
    | '/oidc/userinfo'
    | '/user/$userId'
    | '/user/access'
    | '/user/api-keys'
    | '/user/authority'
    | '/user/cards'
    | '/user/chat'
    | '/user/credits'
    | '/user/plans-and-budgets'
    | '/user/request-history'
    | '/user/tools'
    | '/user'
    | '/user/access/access-points'
    | '/user/access/available-models'
    | '/user/access/order'
    | '/user/account/security'
    | '/user/keys/$keyId'
    | '/user/plans-and-budgets/budget'
    | '/user/plans-and-budgets/plans'
    | '/user/tools/api-test'
    | '/user/account'
    | '/user/keys'
    | '/user/team'
    | '/user/team/$teamId/usage'
    | '/user/team/$teamId'
  id:
    | '__root__'
    | '/'
    | '/key'
    | '/login'
    | '/register'
    | '/user'
    | '/.well-known/openid-configuration'
    | '/activate/card'
    | '/api/$'
    | '/auth/landing-entry'
    | '/oidc/authorize'
    | '/oidc/jwks'
    | '/oidc/revoke'
    | '/oidc/token'
    | '/oidc/userinfo'
    | '/user/$userId'
    | '/user/access'
    | '/user/account'
    | '/user/api-keys'
    | '/user/authority'
    | '/user/cards'
    | '/user/chat'
    | '/user/credits'
    | '/user/keys'
    | '/user/plans-and-budgets'
    | '/user/request-history'
    | '/user/team'
    | '/user/tools'
    | '/user/'
    | '/user/access/access-points'
    | '/user/access/available-models'
    | '/user/access/order'
    | '/user/account/security'
    | '/user/keys/$keyId'
    | '/user/plans-and-budgets/budget'
    | '/user/plans-and-budgets/plans'
    | '/user/team/$teamId'
    | '/user/tools/api-test'
    | '/user/account/'
    | '/user/keys/'
    | '/user/team/'
    | '/user/team/$teamId/usage'
    | '/user/team/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeyRoute: typeof KeyRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UserRoute: typeof UserRouteWithChildren
  Char91DotwellKnownChar93OpenidConfigurationRoute: typeof Char91DotwellKnownChar93OpenidConfigurationRoute
  ActivateCardRoute: typeof ActivateCardRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthLandingEntryRoute: typeof AuthLandingEntryRoute
  OidcAuthorizeRoute: typeof OidcAuthorizeRoute
  OidcJwksRoute: typeof OidcJwksRoute
  OidcRevokeRoute: typeof OidcRevokeRoute
  OidcTokenRoute: typeof OidcTokenRoute
  OidcUserinfoRoute: typeof OidcUserinfoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key': {
      id: '/key'
      path: '/key'
      fullPath: '/key'
      preLoaderRoute: typeof KeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof Char91DotwellKnownChar93OpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate/card': {
      id: '/activate/card'
      path: '/activate/card'
      fullPath: '/activate/card'
      preLoaderRoute: typeof ActivateCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/landing-entry': {
      id: '/auth/landing-entry'
      path: '/auth/landing-entry'
      fullPath: '/auth/landing-entry'
      preLoaderRoute: typeof AuthLandingEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc/authorize': {
      id: '/oidc/authorize'
      path: '/oidc/authorize'
      fullPath: '/oidc/authorize'
      preLoaderRoute: typeof OidcAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc/jwks': {
      id: '/oidc/jwks'
      path: '/oidc/jwks'
      fullPath: '/oidc/jwks'
      preLoaderRoute: typeof OidcJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc/revoke': {
      id: '/oidc/revoke'
      path: '/oidc/revoke'
      fullPath: '/oidc/revoke'
      preLoaderRoute: typeof OidcRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc/token': {
      id: '/oidc/token'
      path: '/oidc/token'
      fullPath: '/oidc/token'
      preLoaderRoute: typeof OidcTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc/userinfo': {
      id: '/oidc/userinfo'
      path: '/oidc/userinfo'
      fullPath: '/oidc/userinfo'
      preLoaderRoute: typeof OidcUserinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/access': {
      id: '/user/access'
      path: '/access'
      fullPath: '/user/access'
      preLoaderRoute: typeof UserAccessRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/account': {
      id: '/user/account'
      path: '/account'
      fullPath: '/user/account'
      preLoaderRoute: typeof UserAccountRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/api-keys': {
      id: '/user/api-keys'
      path: '/api-keys'
      fullPath: '/user/api-keys'
      preLoaderRoute: typeof UserApiKeysRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/authority': {
      id: '/user/authority'
      path: '/authority'
      fullPath: '/user/authority'
      preLoaderRoute: typeof UserAuthorityRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/cards': {
      id: '/user/cards'
      path: '/cards'
      fullPath: '/user/cards'
      preLoaderRoute: typeof UserCardsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/chat': {
      id: '/user/chat'
      path: '/chat'
      fullPath: '/user/chat'
      preLoaderRoute: typeof UserChatRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/credits': {
      id: '/user/credits'
      path: '/credits'
      fullPath: '/user/credits'
      preLoaderRoute: typeof UserCreditsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/keys': {
      id: '/user/keys'
      path: '/keys'
      fullPath: '/user/keys'
      preLoaderRoute: typeof UserKeysRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/plans-and-budgets': {
      id: '/user/plans-and-budgets'
      path: '/plans-and-budgets'
      fullPath: '/user/plans-and-budgets'
      preLoaderRoute: typeof UserPlansAndBudgetsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/request-history': {
      id: '/user/request-history'
      path: '/request-history'
      fullPath: '/user/request-history'
      preLoaderRoute: typeof UserRequestHistoryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/team': {
      id: '/user/team'
      path: '/team'
      fullPath: '/user/team'
      preLoaderRoute: typeof UserTeamRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/tools': {
      id: '/user/tools'
      path: '/tools'
      fullPath: '/user/tools'
      preLoaderRoute: typeof UserToolsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/access/access-points': {
      id: '/user/access/access-points'
      path: '/access-points'
      fullPath: '/user/access/access-points'
      preLoaderRoute: typeof UserAccessAccessPointsRouteImport
      parentRoute: typeof UserAccessRoute
    }
    '/user/access/available-models': {
      id: '/user/access/available-models'
      path: '/available-models'
      fullPath: '/user/access/available-models'
      preLoaderRoute: typeof UserAccessAvailableModelsRouteImport
      parentRoute: typeof UserAccessRoute
    }
    '/user/access/order': {
      id: '/user/access/order'
      path: '/order'
      fullPath: '/user/access/order'
      preLoaderRoute: typeof UserAccessOrderRouteImport
      parentRoute: typeof UserAccessRoute
    }
    '/user/account/': {
      id: '/user/account/'
      path: '/'
      fullPath: '/user/account/'
      preLoaderRoute: typeof UserAccountIndexRouteImport
      parentRoute: typeof UserAccountRoute
    }
    '/user/account/security': {
      id: '/user/account/security'
      path: '/security'
      fullPath: '/user/account/security'
      preLoaderRoute: typeof UserAccountSecurityRouteImport
      parentRoute: typeof UserAccountRoute
    }
    '/user/keys/': {
      id: '/user/keys/'
      path: '/'
      fullPath: '/user/keys/'
      preLoaderRoute: typeof UserKeysIndexRouteImport
      parentRoute: typeof UserKeysRoute
    }
    '/user/keys/$keyId': {
      id: '/user/keys/$keyId'
      path: '/$keyId'
      fullPath: '/user/keys/$keyId'
      preLoaderRoute: typeof UserKeysKeyIdRouteImport
      parentRoute: typeof UserKeysRoute
    }
    '/user/plans-and-budgets/budget': {
      id: '/user/plans-and-budgets/budget'
      path: '/budget'
      fullPath: '/user/plans-and-budgets/budget'
      preLoaderRoute: typeof UserPlansAndBudgetsBudgetRouteImport
      parentRoute: typeof UserPlansAndBudgetsRoute
    }
    '/user/plans-and-budgets/plans': {
      id: '/user/plans-and-budgets/plans'
      path: '/plans'
      fullPath: '/user/plans-and-budgets/plans'
      preLoaderRoute: typeof UserPlansAndBudgetsPlansRouteImport
      parentRoute: typeof UserPlansAndBudgetsRoute
    }
    '/user/team/': {
      id: '/user/team/'
      path: '/'
      fullPath: '/user/team/'
      preLoaderRoute: typeof UserTeamIndexRouteImport
      parentRoute: typeof UserTeamRoute
    }
    '/user/team/$teamId': {
      id: '/user/team/$teamId'
      path: '/$teamId'
      fullPath: '/user/team/$teamId'
      preLoaderRoute: typeof UserTeamTeamIdRouteImport
      parentRoute: typeof UserTeamRoute
    }
    '/user/tools/api-test': {
      id: '/user/tools/api-test'
      path: '/api-test'
      fullPath: '/user/tools/api-test'
      preLoaderRoute: typeof UserToolsApiTestRouteImport
      parentRoute: typeof UserToolsRoute
    }
    '/user/team/$teamId/': {
      id: '/user/team/$teamId/'
      path: '/'
      fullPath: '/user/team/$teamId/'
      preLoaderRoute: typeof UserTeamTeamIdIndexRouteImport
      parentRoute: typeof UserTeamTeamIdRoute
    }
    '/user/team/$teamId/usage': {
      id: '/user/team/$teamId/usage'
      path: '/usage'
      fullPath: '/user/team/$teamId/usage'
      preLoaderRoute: typeof UserTeamTeamIdUsageRouteImport
      parentRoute: typeof UserTeamTeamIdRoute
    }
  }
}

interface UserAccessRouteChildren {
  UserAccessAccessPointsRoute: typeof UserAccessAccessPointsRoute
  UserAccessAvailableModelsRoute: typeof UserAccessAvailableModelsRoute
  UserAccessOrderRoute: typeof UserAccessOrderRoute
}

const UserAccessRouteChildren: UserAccessRouteChildren = {
  UserAccessAccessPointsRoute: UserAccessAccessPointsRoute,
  UserAccessAvailableModelsRoute: UserAccessAvailableModelsRoute,
  UserAccessOrderRoute: UserAccessOrderRoute,
}

const UserAccessRouteWithChildren = UserAccessRoute._addFileChildren(
  UserAccessRouteChildren,
)

interface UserAccountRouteChildren {
  UserAccountSecurityRoute: typeof UserAccountSecurityRoute
  UserAccountIndexRoute: typeof UserAccountIndexRoute
}

const UserAccountRouteChildren: UserAccountRouteChildren = {
  UserAccountSecurityRoute: UserAccountSecurityRoute,
  UserAccountIndexRoute: UserAccountIndexRoute,
}

const UserAccountRouteWithChildren = UserAccountRoute._addFileChildren(
  UserAccountRouteChildren,
)

interface UserKeysRouteChildren {
  UserKeysKeyIdRoute: typeof UserKeysKeyIdRoute
  UserKeysIndexRoute: typeof UserKeysIndexRoute
}

const UserKeysRouteChildren: UserKeysRouteChildren = {
  UserKeysKeyIdRoute: UserKeysKeyIdRoute,
  UserKeysIndexRoute: UserKeysIndexRoute,
}

const UserKeysRouteWithChildren = UserKeysRoute._addFileChildren(
  UserKeysRouteChildren,
)

interface UserPlansAndBudgetsRouteChildren {
  UserPlansAndBudgetsBudgetRoute: typeof UserPlansAndBudgetsBudgetRoute
  UserPlansAndBudgetsPlansRoute: typeof UserPlansAndBudgetsPlansRoute
}

const UserPlansAndBudgetsRouteChildren: UserPlansAndBudgetsRouteChildren = {
  UserPlansAndBudgetsBudgetRoute: UserPlansAndBudgetsBudgetRoute,
  UserPlansAndBudgetsPlansRoute: UserPlansAndBudgetsPlansRoute,
}

const UserPlansAndBudgetsRouteWithChildren =
  UserPlansAndBudgetsRoute._addFileChildren(UserPlansAndBudgetsRouteChildren)

interface UserTeamTeamIdRouteChildren {
  UserTeamTeamIdUsageRoute: typeof UserTeamTeamIdUsageRoute
  UserTeamTeamIdIndexRoute: typeof UserTeamTeamIdIndexRoute
}

const UserTeamTeamIdRouteChildren: UserTeamTeamIdRouteChildren = {
  UserTeamTeamIdUsageRoute: UserTeamTeamIdUsageRoute,
  UserTeamTeamIdIndexRoute: UserTeamTeamIdIndexRoute,
}

const UserTeamTeamIdRouteWithChildren = UserTeamTeamIdRoute._addFileChildren(
  UserTeamTeamIdRouteChildren,
)

interface UserTeamRouteChildren {
  UserTeamTeamIdRoute: typeof UserTeamTeamIdRouteWithChildren
  UserTeamIndexRoute: typeof UserTeamIndexRoute
}

const UserTeamRouteChildren: UserTeamRouteChildren = {
  UserTeamTeamIdRoute: UserTeamTeamIdRouteWithChildren,
  UserTeamIndexRoute: UserTeamIndexRoute,
}

const UserTeamRouteWithChildren = UserTeamRoute._addFileChildren(
  UserTeamRouteChildren,
)

interface UserToolsRouteChildren {
  UserToolsApiTestRoute: typeof UserToolsApiTestRoute
}

const UserToolsRouteChildren: UserToolsRouteChildren = {
  UserToolsApiTestRoute: UserToolsApiTestRoute,
}

const UserToolsRouteWithChildren = UserToolsRoute._addFileChildren(
  UserToolsRouteChildren,
)

interface UserRouteChildren {
  UserUserIdRoute: typeof UserUserIdRoute
  UserAccessRoute: typeof UserAccessRouteWithChildren
  UserAccountRoute: typeof UserAccountRouteWithChildren
  UserApiKeysRoute: typeof UserApiKeysRoute
  UserAuthorityRoute: typeof UserAuthorityRoute
  UserCardsRoute: typeof UserCardsRoute
  UserChatRoute: typeof UserChatRoute
  UserCreditsRoute: typeof UserCreditsRoute
  UserKeysRoute: typeof UserKeysRouteWithChildren
  UserPlansAndBudgetsRoute: typeof UserPlansAndBudgetsRouteWithChildren
  UserRequestHistoryRoute: typeof UserRequestHistoryRoute
  UserTeamRoute: typeof UserTeamRouteWithChildren
  UserToolsRoute: typeof UserToolsRouteWithChildren
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserUserIdRoute: UserUserIdRoute,
  UserAccessRoute: UserAccessRouteWithChildren,
  UserAccountRoute: UserAccountRouteWithChildren,
  UserApiKeysRoute: UserApiKeysRoute,
  UserAuthorityRoute: UserAuthorityRoute,
  UserCardsRoute: UserCardsRoute,
  UserChatRoute: UserChatRoute,
  UserCreditsRoute: UserCreditsRoute,
  UserKeysRoute: UserKeysRouteWithChildren,
  UserPlansAndBudgetsRoute: UserPlansAndBudgetsRouteWithChildren,
  UserRequestHistoryRoute: UserRequestHistoryRoute,
  UserTeamRoute: UserTeamRouteWithChildren,
  UserToolsRoute: UserToolsRouteWithChildren,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeyRoute: KeyRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UserRoute: UserRouteWithChildren,
  Char91DotwellKnownChar93OpenidConfigurationRoute:
    Char91DotwellKnownChar93OpenidConfigurationRoute,
  ActivateCardRoute: ActivateCardRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthLandingEntryRoute: AuthLandingEntryRoute,
  OidcAuthorizeRoute: OidcAuthorizeRoute,
  OidcJwksRoute: OidcJwksRoute,
  OidcRevokeRoute: OidcRevokeRoute,
  OidcTokenRoute: OidcTokenRoute,
  OidcUserinfoRoute: OidcUserinfoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
