import { Button } from "@frely/ui/components/button";
import { Card } from "@frely/ui/components/card";
import { MaterialTablePagination } from "@frely/console-ui/material-table-pagination";
import Link from "@admin/navigation";
import { DirectoryPanel } from "../../../pages/owner/_components/directory-panel";
import { MetricCard, PageHeading } from "../../../pages/owner/_components/ui";
import type { AdminCreditsAggregate } from "../../../lib/teams";
import { adminCreditsHref, type AdminCreditsUrlState } from "../lib/credit-url-state";
import type { CreditConfigurationSummary, CreditTopup, PaymentChannel } from "../types";
import { CreditConfiguration } from "./credit-configuration";
import { CreditsTable, CreditScopeSummaryTable } from "./credits-table";
import { CreditTopups } from "./credit-topups";

export function CreditsView({ state, credits, topups, topupCursor, topupNextHref, configuration, draftChannels, configurationPage }: { state: AdminCreditsUrlState; credits: AdminCreditsAggregate; topups: CreditTopup[]; topupCursor: string; topupNextHref: string; configuration: CreditConfigurationSummary; draftChannels: PaymentChannel[]; configurationPage: { page: number; pageSize: number; total: number; totalPages: number } }) {
  return <>
    <PageHeading eyebrow="Credit Overview" title="Credits" description="Review user balances across teams, transfer-out policy state, and non-user scope summaries."><Button variant="secondary" asChild><Link href="/owner/users">Users</Link></Button></PageHeading>
    <section className="summary-row">{credits.metrics.map((metric) => <MetricCard key={metric.label} label={metric.label} value={metric.value} detail={metric.detail} {...(metric.tone ? { tone: metric.tone } : {})} />)}</section>
    <Card className="panel"><div className="panel-heading"><div><h2>Credit Topups</h2><p className="muted">Manual review queue and runtime Credit configuration.</p></div></div><CreditConfiguration summary={configuration} draftChannels={draftChannels} /><MaterialTablePagination page={configurationPage.page} pageSize={configurationPage.pageSize} total={configurationPage.total} totalPages={configurationPage.totalPages} pageParam="configurationPage" pageSizeParam="configurationPageSize" previousHref={configurationPage.page > 1 ? adminCreditsHref({ ...state, configurationPage: configurationPage.page - 1 }) : ""} nextHref={configurationPage.page < configurationPage.totalPages ? adminCreditsHref({ ...state, configurationPage: configurationPage.page + 1 }) : ""} noun="draft payment channels" /><CreditTopups topups={topups} /><MaterialTablePagination page={1} pageSize={state.topupPageSize} pageSizeParam="topupPageSize" resetParams={["topupCursor"]} total={topups.length} totalMode="unknown" totalPages={1} nextHref={topupNextHref} noun="topups" /></Card>
    <DirectoryPanel title="User Credit Directory" description="Search by user, team, account, or account status." action="/owner/credits" query={credits.query} placeholder="Search credits by user, team, account, or status" emptyLabel="No user credit rows match this search." hasRows={credits.rows.length > 0} hiddenParams={{ pageSize: credits.pageSize === 20 ? undefined : credits.pageSize, scopePageSize: state.scopePageSize === 20 ? undefined : state.scopePageSize, configurationPageSize: state.configurationPageSize === 20 ? undefined : state.configurationPageSize, topupPageSize: state.topupPageSize === 20 ? undefined : state.topupPageSize }}><CreditsTable rows={credits.rows} /><MaterialTablePagination page={credits.page} pageSize={credits.pageSize} total={credits.total} totalPages={credits.totalPages} rangeStart={credits.total ? (credits.page - 1) * credits.pageSize + 1 : 0} rangeEnd={Math.min(credits.page * credits.pageSize, credits.total)} previousHref={credits.page > 1 ? adminCreditsHref({ ...state, page: credits.page - 1 }) : ""} nextHref={credits.page < credits.totalPages ? adminCreditsHref({ ...state, page: credits.page + 1 }) : ""} noun="user credit accounts" /></DirectoryPanel>
    <Card className="panel"><div className="panel-heading"><div><h2>Team / Global Scope Summary</h2><p className="muted">Non-user accounts are summarized here and excluded from the user directory.</p></div></div><CreditScopeSummaryTable rows={credits.scopeSummary} /><MaterialTablePagination page={credits.scopePage} pageSize={credits.scopePageSize} total={credits.scopeTotal} totalPages={credits.scopeTotalPages} pageParam="scopePage" pageSizeParam="scopePageSize" rangeStart={credits.scopeTotal ? (credits.scopePage - 1) * credits.scopePageSize + 1 : 0} rangeEnd={Math.min(credits.scopePage * credits.scopePageSize, credits.scopeTotal)} previousHref={credits.scopePage > 1 ? adminCreditsHref({ ...state, scopePage: credits.scopePage - 1 }) : ""} nextHref={credits.scopePage < credits.scopeTotalPages ? adminCreditsHref({ ...state, scopePage: credits.scopePage + 1 }) : ""} noun="non-user credit accounts" /></Card>
  </>;
}
